namespace SpriteKind {
    export const Questgiver = SpriteKind.create()
    export const Info = SpriteKind.create()
    export const StatusBar = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`Door`, function (sprite, location) {
    if (info.score() == 3) {
        game.over(true)
    } else {
        game.showLongText("Du hast noch nicht alle Schlüssel gefunden...", DialogLayout.Bottom)
    }
})
function generateEnemy () {
    QuestGiver = sprites.create(img`
        . . . . c c c c c c c . . . . . 
        . . . . . b b b b b . . . . . . 
        . . . . f f f f f f f . . . . . 
        . . . d d d d f d d d d . . . . 
        . . . d f f d d d f f d . . . . 
        . . . d f 1 d 4 d 1 f d . . . . 
        . . . d d d d 4 d d d d . . . . 
        . . . f f f f 4 f f f f . . . . 
        . . . c b b f f f b b c . . . . 
        . . . c b b b b b b b c . . . . 
        . . . c b b b b b b b c . . . . 
        . . . c b b b b b b b c . . . . 
        . . . . e e e e e e e . . . . . 
        . . . . e e e . e e e . . . . . 
        . . . . . f . . . f . . . . . . 
        . . . 4 4 4 4 . 4 4 4 4 . . . . 
        `, SpriteKind.Questgiver)
    tiles.placeOnTile(QuestGiver, tiles.getTileLocation(10, 1))
    InfoGiver = sprites.create(img`
        . . . . . . . 5 . . . . . . . . 
        . . . . . 5 5 5 5 5 . . . . . . 
        . . . . 5 5 5 5 5 5 5 . . . . . 
        . . . . 5 5 5 5 5 5 5 . . . . . 
        . . . . 5 f 5 5 5 f 5 . . . . . 
        . . . . 5 5 4 4 4 5 5 . . . . . 
        . . . . 5 5 5 4 5 5 5 . . . . . 
        . . . 5 6 6 5 4 5 6 6 5 . . . . 
        . . . 5 6 6 5 5 5 6 6 5 . . . . 
        . . . 5 6 6 6 6 6 6 6 5 . . . . 
        . . . 5 6 6 6 6 6 6 6 5 . . . . 
        . . . 5 6 6 6 6 6 6 6 5 . . . . 
        . . . . 6 6 6 6 6 6 6 . . . . . 
        . . . . 6 6 6 . 6 6 6 . . . . . 
        . . . . . 5 . . . 5 . . . . . . 
        . . . 4 4 4 4 . 4 4 4 4 . . . . 
        `, SpriteKind.Info)
    tiles.placeOnTile(InfoGiver, tiles.getTileLocation(23, 23))
    animation.runMovementAnimation(
    InfoGiver,
    animation.animationPresets(animation.bobbing),
    5000,
    true
    )
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Crow,
    [img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f f f f . 
        . . . f f f f f f f f f f f . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . f f f f f f f f f f f . . . 
        . f f f f f f f f f f f f . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . 4 . . . f f f . . . . 
        . . . . 4 4 4 . . . f . . . . . 
        . . . . . . . . . . 4 . . . . . 
        . . . . . . . . . 4 4 4 . . . . 
        `,img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . f f f f f f f f f f f f . . . 
        . . f f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f f . . 
        . . . f f f f f f f f f f f f . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f . . . 4 . . . . . 
        . . . . . f . . . 4 4 4 . . . . 
        . . . . . 4 . . . . . . . . . . 
        . . . . 4 4 4 . . . . . . . . . 
        `],
    200,
    true
    )
})
function EnemyWatch () {
    Ghost1 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Ghost1, tiles.getTileLocation(6, 1.5))
    animation.runMovementAnimation(
    Ghost1,
    animation.animationPresets(animation.bobbing),
    2000,
    true
    )
    Ghost2 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Ghost2, tiles.getTileLocation(20, 21))
    animation.runMovementAnimation(
    Ghost2,
    animation.animationPresets(animation.bobbing),
    2000,
    true
    )
    Ghost3 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Ghost3, tiles.getTileLocation(8, 13))
    animation.runMovementAnimation(
    Ghost3,
    animation.animationPresets(animation.shake),
    2000,
    true
    )
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . 4 d e 4 . . . . . . 
        . . . . 4 4 d 4 f e 4 . . . . . 
        . . . . e f d d d e 4 . . . . . 
        . . . . e f f d e f 4 4 . . . . 
        . . . . 4 d d e f f 4 . . . . . 
        . . . . . d d e f e . . . . . . 
        . . . . . . 4 d d . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, Crow, 100, 0)
})
controller.anyButton.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, Crow)
    Crow.setImage(img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f 1 f f 1 f f . . . . 
        . . . . f f f 4 4 f f f . . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . f f f f f f f f f f f f . . 
        . . f f f f f f f f f f f f . . 
        . . f f f f f f f f f f f f . . 
        . . f f f f f f f f f f f f . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f . . f f f . . . . 
        . . . . . f . . . . f . . . . . 
        . . . . . 4 . . . . 4 . . . . . 
        . . . . 4 4 4 . . 4 4 4 . . . . 
        `)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Crow,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f 1 f f f f . . . . . 
        . . . 4 4 f f f f f f . . . . . 
        . . . . 4 f f f f f f f f f f f 
        . . . . . f f f f f f f f f f . 
        . . . . . f f f f f f f f f . . 
        . . . . . f f f f f f f f . . . 
        . . . . . f f f f f f f . . . . 
        . . . . . f f f f f f f . . . . 
        . . 4 . f f f f f f f f . . . . 
        . . 4 4 f f f f f f f f . . . . 
        . . 4 . f f f . . f f f . . . . 
        . . . . . . . . . . 4 . . . . . 
        . . . . . . . . . 4 4 4 . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f 1 f f f f . . . . . 
        . . . 4 4 f f f f f f . . . . . 
        . . . . 4 f f f f f f . . . . . 
        f f f f f f f f f f f . . . . . 
        . f f f f f f f f f f . . . . . 
        . . f f f f f f f f f . . . . . 
        . . . f f f f f f f f . . . . . 
        . . . . f f f f f f f . . . . . 
        . . . . f f f f f f f f . 4 . . 
        . . . . f f f f f f f f 4 4 . . 
        . . . . f f f . . f f f . 4 . . 
        . . . . . 4 . . . . . . . . . . 
        . . . . 4 4 4 . . . . . . . . . 
        `],
    200,
    true
    )
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Info, function (sprite, otherSprite) {
    giveInfo = 1
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`Key`, function (sprite, location) {
    info.changeScoreBy(1)
    tiles.setTileAt(location, sprites.castle.tileDarkGrass2)
})
info.onCountdownEnd(function () {
    game.over(false)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Crow,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f f f 1 f . . . . . 
        . . . . . f f f f f f 4 4 . . . 
        f f f f f f f f f f f 4 . . . . 
        . f f f f f f f f f f . . . . . 
        . . f f f f f f f f f . . . . . 
        . . . f f f f f f f f . . . . . 
        . . . . f f f f f f f . . . . . 
        . . . . f f f f f f f . . . . . 
        . . . . f f f f f f f f . 4 . . 
        . . . . f f f f f f f f 4 4 . . 
        . . . . f f f . . f f f . 4 . . 
        . . . . . 4 . . . . . . . . . . 
        . . . . 4 4 4 . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f f f 1 f . . . . . 
        . . . . . f f f f f f 4 4 . . . 
        . . . . . f f f f f f 4 . . . . 
        . . . . . f f f f f f f f f f f 
        . . . . . f f f f f f f f f f . 
        . . . . . f f f f f f f f f . . 
        . . . . . f f f f f f f f . . . 
        . . . . . f f f f f f f . . . . 
        . . 4 . f f f f f f f f . . . . 
        . . 4 4 f f f f f f f f . . . . 
        . . 4 . f f f . . f f f . . . . 
        . . . . . . . . . . 4 . . . . . 
        . . . . . . . . . 4 4 4 . . . . 
        `],
    200,
    true
    )
})
scene.onOverlapTile(SpriteKind.Projectile, sprites.castle.rock0, function (sprite, location) {
    tiles.setWallAt(location, false)
    tiles.setTileAt(location, sprites.castle.tileDarkGrass2)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Questgiver, function (sprite, otherSprite) {
    QuestDialog = 1
    canBomb = 1
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Crow,
    [img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f 1 f f 1 f f . . . . 
        . . . . f f f 4 4 f f f . . . . 
        . . . f f f f f f f f f f f f . 
        . . . f f f f f f f f f f f . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . f f f f f f f f f f f . . . 
        . f f f f f f f f f f f f . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . 4 . . . f f f . . . . 
        . . . . 4 4 4 . . . f . . . . . 
        . . . . . . . . . . 4 . . . . . 
        . . . . . . . . . 4 4 4 . . . . 
        `,img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f 1 f f 1 f f . . . . 
        . . . . f f f 4 4 f f f . . . . 
        . f f f f f f f f f f f f . . . 
        . . f f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f f . . 
        . . . f f f f f f f f f f f f . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f . . . 4 . . . . . 
        . . . . . f . . . 4 4 4 . . . . 
        . . . . . 4 . . . . . . . . . . 
        . . . . 4 4 4 . . . . . . . . . 
        `],
    200,
    true
    )
})
controller.B.onEvent(ControllerButtonEvent.Released, function () {
    if (canBomb == 1) {
        Bombe = sprites.createProjectileFromSprite(img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ...............22...............
            ..............3113..............
            .............211112.............
            .............211112.............
            ..............3113..............
            ...............22...............
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            `, Crow, 0, 0)
        Bombe.setFlag(SpriteFlag.GhostThroughWalls, true)
        animation.runImageAnimation(
        Bombe,
        [img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ...............33...............
            ..............3113..............
            ..............3113..............
            ..........32231111322...........
            ..........331111111133..........
            ..........331111111133..........
            ...........3111111113...........
            ............31111113............
            ............21111112............
            ............21133112............
            ............33322233............
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            `,img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ...............22...............
            ..............3113..............
            .............211112.............
            .............211112.............
            ..............3113..............
            ...............22...............
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            `,img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ...............33...............
            ...............313..............
            ...........33..313..33..........
            ...........313.3132313..........
            ............313313213...........
            .........33332131113............
            .........3111111112333333.......
            ..........333231111111113.......
            ..............2111332333........
            .............3131312............
            ............313213313...........
            ...........313.213.313..........
            ...........33..313..33..........
            ...............313..............
            ...............313..............
            ...............33...............
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            `,img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ..........33...33...............
            .........3112..313..333.........
            .........3112..313.3113.........
            ..........322..212.2113.........
            .........33.....22.222..........
            ........31122.......33..........
            ........31112......21133........
            ........3112......311113........
            .........322.......2113.........
            ...............2....33..........
            ..........222.212..222..........
            .........311223112.21133........
            ........3111221112.21113........
            ........3113..313...3113........
            ........333....33....33.........
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            `,img`
            .................3..............
            .....3.....................3..3.
            ..............................33
            .........3.....................3
            ........33..........33..........
            .3......3.....3......3......3...
            .3...........33.............33..
            33..............................
            ................................
            ....3....................3......
            ....3.............3......33.....
            .............3....33......3.....
            ............33.....3............
            ............3...3........3......
            .....3..........3........3......
            .....3...3..........3....3......
            ........33..........33..........
            ........3............3......3...
            ................................
            ..3........3...3.....3..........
            ..........33...3.....33.........
            ..........3....3......3...3.....
            ..........................3.....
            .....3....................33....
            ....33.....................3....
            ....3......................3....
            ....3........3......3...........
            .............3......3...........
            ..3.............................
            ..........3...................3.
            ........................3.......
            ................................
            `,img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            `],
        100,
        false
        )
    }
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprite.destroy()
    otherSprite.destroy()
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    game.over(false)
})
let Bombe: Sprite = null
let giveInfo = 0
let projectile: Sprite = null
let Ghost3: Sprite = null
let Ghost2: Sprite = null
let Ghost1: Sprite = null
let InfoGiver: Sprite = null
let QuestGiver: Sprite = null
let canBomb = 0
let QuestDialog = 0
let Crow: Sprite = null
scene.setBackgroundColor(6)
tiles.setTilemap(tilemap`Level1`)
Crow = sprites.create(img`
    . . . . . f f f f f f . . . . . 
    . . . . f f f f f f f f . . . . 
    . . . . f f f f f f f f . . . . 
    . . . . f f 1 f f 1 f f . . . . 
    . . . . f f f 4 4 f f f . . . . 
    . . . f f f f f f f f f f . . . 
    . . . f f f f f f f f f f . . . 
    . . f f f f f f f f f f f f . . 
    . . f f f f f f f f f f f f . . 
    . . f f f f f f f f f f f f . . 
    . . f f f f f f f f f f f f . . 
    . . . . f f f f f f f f . . . . 
    . . . . f f f . . f f f . . . . 
    . . . . . f . . . . f . . . . . 
    . . . . . 4 . . . . 4 . . . . . 
    . . . . 4 4 4 . . 4 4 4 . . . . 
    `, SpriteKind.Player)
Crow.setPosition(50, 480)
controller.moveSprite(Crow, 150, 150)
scene.cameraFollowSprite(Crow)
generateEnemy()
EnemyWatch()
QuestDialog = 0
canBomb = 1
game.showLongText("Drücke A, um Gegner abzuschießen.", DialogLayout.Bottom)
info.startCountdown(200)
forever(function () {
    if (QuestDialog == 1) {
        game.showLongText("Danke für deine Hilfe! Hier, nimm dieses Geschenk.", DialogLayout.Bottom)
        game.showLongText("Es wird dir helfen, von hier zu entkommen.", DialogLayout.Bottom)
        game.showLongText("Drücke B, um Bomben zu platzieren.", DialogLayout.Bottom)
        pause(2000)
        QuestDialog = 0
    }
})
forever(function () {
    if (giveInfo == 1) {
        game.showLongText("Sprenge die Felsen, die dir den Weg versperren.", DialogLayout.Bottom)
        game.showLongText("Und sammle alle Schlüssel, um zu entkommen.", DialogLayout.Bottom)
        game.showLongText("Viel Glück!", DialogLayout.Bottom)
        pause(2000)
        giveInfo = 0
    }
})
